apiVersion: v1
kind: Pod
metadata:
    name: memberapi
spec: 
    containers:
    - name: memberapi
      image: membersapi:local
      ports:
      - containerPort: 80
        resources:
# kubectl create -f nginx.pod.yml --save-config
# kubectl describe pod [pod-name]
# kubectl apply -f nginx.pod.yml
# kubectl exec -f [pod-name] -it sh
# kubectl edit -f nginx.pod.yml
# kubectl delete -f nginx.pod.yml